/*
 * Copyright 2023-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.github.aimodel.model;

/**
 * 此接口提供了访问AI模型的主要输出和与此结果相关的元数据的方法。
 * 它旨在提供一种标准化和全面的方法来处理和解释人工智能模型生成的输出，
 * 以满足不同的人工智能应用程序和用例。
 *
 * @param <T> the type of the output generated by the AI model
 * @author Mark Pollack
 * @since 0.8.0
 */
public interface ModelResult<T> {

    /**
     * 检索AI模型生成的输出。
     *
     * @return the output generated by the AI model
     */
    T getOutput();

    /**
     * 检索与AI模型结果关联的元数据。
     *
     * @return the metadata associated with the result
     */
    ResultMetadata getMetadata();

}